name: GLaDOS Checkin

on:
  schedule:
  - cron: '0 1 * * *'

  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    timeout-minutes: 5
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install node-fetch@3.x

      - name: Run checkin
        env:
          GLADOS_1: ${{ secrets.GLADOS }} # 账户1
          GLADOS_2: ${{ secrets.GLADOS2 }} # 账户2
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
        run: node main.js
