name: Checkin Bot

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "10 16 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    env:  # ✅ 全局环境变量
      GLADOS: ${{ secrets.GLADOS }}
      GLADOS2: ${{ secrets.GLADOS2 }}
      DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
      DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
      NOTIFY: ${{ secrets.NOTIFY }}
      NOTIFY2: ${{ secrets.NOTIFY2 }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: |
          npm ci --loglevel verbose  # ✅ 启用详细日志
          echo "NODE_PATH=$(npm root -g)" >> $GITHUB_ENV

      - name: Run Checkin
        run: npm run main
        env:
          # 覆盖调试级别（可选）
          NODE_DEBUG: "fetch,http"
